import Head from "next/head";
import Sponsor from "@/components/display/Sponsor";
import styles from "@/styles/Subpage.module.css";
import Image from "next/image";
import sponsor from "@/assets/sponsor.png";
import LabeledDivider from "@/components/dividers/LabeledDivider";
import ContactSection from "@/components/sections/ContactSection";

export default function SponsorPage() {
  return (
    <>
      <Head>
        <title>Sponsor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.subpage_hero}>
          <Image className={styles.contribute_img} src={sponsor} alt="image of people looking at the screen" height={400} layout="responsive" />
          <div className={styles.contribute_display}>
            <Sponsor />
          </div>
        </div>
        <div className={styles.contribute_info}>
          <h1>Enhance Cinematic Experiences</h1>
          <p>
            CinWwine is a monthly free-of-charge event, but we continually strive to elevate the experience for our cherished attendees. We are actively seeking sponsorships to further enrich the moments we create. As our name suggests, we ideally
            try to unite cinema lovers and wine enthusiasts alike.
          </p>

          <p>
            Your sponsorship, whether through donations, lottery contributions, offering discounts, or hosting product/wine tastings, will significantly contribute to our goal. In return, we guarantee brand promotion across our active social media
            platforms, ensuring visibility to our engaged audience.
          </p>

          <p>Partner with CineWine and become an integral part of crafting unforgettable moments in community. Reach out to us today and let&apos;s create meaningful connections.</p>
        </div>

        <div className={styles.contribute_form}>
          <LabeledDivider label={"Get in touch"} />
          <ContactSection />
        </div>
      </main>
    </>
  );
}
