import Head from "next/head";
import Volunteer from "@/components/display/Volunteer";
import styles from "@/styles/Subpage.module.css";
import Image from "next/image";
import volunteer from "@/assets/volunteer.png";
import LabeledDivider from "@/components/dividers/LabeledDivider";
import ContactSection from "@/components/sections/ContactSection";

export default function VolunteerPage() {
  return (
    <>
      <Head>
        <title>Volunteer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.subpage_hero}>
          <Image className={styles.contribute_img} src={volunteer} alt="image of people looking at the screen" height={400} layout="responsive" />
          <div className={styles.contribute_display}>
            <Volunteer />
          </div>
        </div>
        <div className={styles.contribute_info}>
          <h1>
            Cinema. Connection. Community.
            <br /> Join Us
          </h1>
          <p>We are seeking enthusiasts who share our passion and can contribute to achieving CineWine's goal: fostering a vibrant space where unconventional cinema and meaningful connections flourish.</p>

          <p>
            As a CineWine volunteer, you'll have the opportunity to connect and engage with fellow cinema enthusiasts. Your contributions will play a vital role in strengthening CineWine's ability to provide a more organized and enhanced experience
            before, during, and after the event.
          </p>

          <p>Together, let's foster a space where cinema and camaraderie converge. Join our journey and help create lasting, unforgettable moments. Complete our form to step into this meaningful adventure!</p>
        </div>
        <LabeledDivider label={"Open positions"} />
        <div className={styles.open_positions}>
          <div>
            <h4 className="label">Social Media & Content Creator</h4>
            <p>Shape Cinewine’ s online presence! Craft engaging posts, share behind-the-scenes moments, and spark conversations across social media platforms. Your creativity brings our cinema community together.</p>
          </div>
          <div>
            <h4 className="label">Event Bar Assistant</h4>
            <p>Dive into the event day action! Assist in setting up the bar and ensure a pleasant experience for attendees. Your energy and efficiency keep the spirits high throughout the event.</p>
          </div>
          <div>
            <h4 className="label">Promotion Manager</h4>
            <p>Fuel Cinewine’ s growth! Manage partnerships, promote the event, and help seek out sponsors. Your strategic approach and networking skills will help support and enhance the Cinewine experience.</p>
          </div>
        </div>
        <div className={styles.contribute_form}>
          <LabeledDivider label={"Get in touch"} />
          <ContactSection />
        </div>
      </main>
    </>
  );
}
