import Head from "next/head";
import UpcomingSection from "@/components/sections/UpcomingSection";
import styles from "@/styles/Subpage.module.css";
import PastEventsSection from "@/components/sections/PastEventsSection";
import ContributeSection from "@/components/sections/ContributeSection";

export default function Events() {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.subpage_hero}>
          <UpcomingSection />
          <PastEventsSection />
          <ContributeSection />
        </div>
      </main>
    </>
  );
}
