import Head from "next/head";
import ContributeSection from "@/components/sections/ContributeSection";
import styles from "@/styles/Subpage.module.css";
import LabeledDivider from "@/components/dividers/LabeledDivider";
import Image from "next/image";
import karolina from "@/assets/karolina.png";
import AnotherChance from "@/components/display/AnotherChance";

export default function Single_event() {
  return (
    <>
      <Head>
        <title>Single Event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.subpage_hero}>
          <div className={styles.single_evt_display}>
            <AnotherChance />
          </div>
          <div className={styles.event_details}>
            <div>
              <h4 className="label">Nr. of event</h4>
              <h3 className={styles.event_nr}>#03</h3>
            </div>
            <div>
              <h4 className="label">Screening date</h4>
              <h3 className={styles.event_date}>03.03.2021</h3>
            </div>
          </div>
          <h2 className={`highlighted ${styles.abstract}`}>An intimate connection forms between an aging actor and a young woman in Tokyo, exploring isolation and cultural barriers.</h2>
        </div>
        <div className={styles.evt_content}>
          <div>
            <h4 className={`label`}>Movie name</h4>
            <h1 className={styles.moviename}>Lost in Translation</h1>
          </div>
          <div className={styles.grid}>
            <Image className={styles.movie_img} src={karolina} alt="portrait of Karolina Curova" height={400} layout="responsive" />
            <LabeledDivider label={"Movie info"} />
            <div className={styles.movie_info}>
              <p>Director: Sofia Coppola</p>
              <p>Runtime: 1 hour 41 minutes</p>
              <p>Language: English, Japanesse</p>
              <p>Main Cast: Bill Murray, Scarlett Johansson</p>
              <p>Location: Primarily filmed in Tokyo, Japan</p>
            </div>
            <p className={styles.long_description}>
              &ldquo;Lost in Translation&rdquo; continues to resonate in today's context of granting ourselves and others a chance for understanding and connection amidst cultural, generational, or personal differences. The film's portrayal of two
              individuals navigating an unfamiliar environment mirrors our modern challenge of bridging gaps and extending empathy in an increasingly diverse and interconnected world. Its central theme of fleeting encounters and missed connections
              reflects the importance of offering second chances, whether in relationships or interactions, emphasizing the significance of patience, empathy, and open-mindedness in fostering meaningful connections in a society often marked by swift
              judgments and misunderstandings.
            </p>
          </div>
        </div>
        <div className={styles.event_group}>
          <div>
            <LabeledDivider label={"Next event"} />
            <Image className={styles.movie_img} src={karolina} alt="portrait of Karolina Curova" height={400} layout="responsive" />
          </div>
          <div>
            <LabeledDivider label={"Previous event"} />
            <Image className={styles.movie_img} src={karolina} alt="portrait of Karolina Curova" height={400} layout="responsive" />
          </div>
        </div>
        <ContributeSection />
      </main>
    </>
  );
}
